---
root: true

plugins:
  - functional

extends:
  - airbnb
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'

parser: '@babel/eslint-parser'

parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  no-console: 'off'
  # no-console: ['error', { allow: ['warn', 'error'] }]
  import/extensions: 'off'
  react/prop-types: 'off'
  functional/no-conditional-statement: 'off'
  functional/no-expression-statement: 'off'
  functional/immutable-data: 'off'
  functional/functional-parameters: 'off'
  functional/no-try-statement: 'off'
  functional/no-throw-statement: 'off'
